/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qjl_nativee_HelloNative */

#ifndef _Included_com_qjl_nativee_HelloNative
#define _Included_com_qjl_nativee_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qjl_nativee_HelloNative
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qjl_nativee_HelloNative_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
